import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const genshin = localFont({
  src: "../assets/fonts/Genshin-Font.ttf",
  variable: "--font-genshin",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${genshin.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
